### ISSUE TITLE
Vérifier les propositions du joueur à l'aide du dictionnaire

### ISSUE THREAD

**Issue by bmaparpaing** [bmaparpaing/compliqom#2]
Chaque mot entré sur une ligne doit être un mot du dictionnaire. Si ce n'est pas le cas, un message doit informer le joueur que le mot est invalide, et le mot entré est effacé.

**Comment by scaunois** [comment]
Je propose d'ajouter à la DoD de ce ticket qu'il faut effacer la saisie de l'utilisateur si le mot entré est invalide, car sinon on ne passe pas à la ligne suivante mais le joueur doit effacer lui-même sa saisie pour pouvoir taper un nouveau mot.

**Comment by bmaparpaing** [comment]
T'es sûr de toi pour ce comportement ? En vrai je trouve ça trop pénible que ça efface le mot, ça aide pas quand on fait du bruteforce...

**Comment by bmaparpaing** [comment]
Vu ensemble, on intègre ta proposition et plus tard on mettra une config au choix de l'utilisateur.
