### ISSUE TITLE
Afficher la définition du mot à trouver

### ISSUE THREAD

**Issue by bmaparpaing** [bmaparpaing/compliqom#7]
Afficher la définition du mot à trouver une fois la partie finie, ou bien proposer un lien vers la définition du mot sur un autre site.

**Comment by scaunois** [comment]
Comme discuté, on va implémenter la solution suivante dans un premier temps : on affiche un lien hypertexte menant vers la page Wikipedia du mot-solution (on suppose qu'elle existe toujours ; si ce n'est pas le cas, on avisera ultérieurement pour améliorer le comportement). Le lien sera de cette forme :
```
https://fr.wikipedia.org/wiki/MOT_SOLUTION
```
avec MOT_SOLUTION étant le mot-solution en minuscule, avec les éventuels accents.
